Adding ability to ignore actuators
lsst-ts/ts_standardscripts pull request #133
Opened 2023-07-11 20:17 UTC by dsanmartim

Hi Tiago,

I did a quick implementation on this ticket. Can you take a look on the first try and tell me if anything else would be needed?

2023-07-11 22:05 UTC, tribeiro requested changes
Please update the version history and take a look at the inline comments I've made. The CI is failing because of the indentation problem I mention on the schema (line 139).

2023-07-11 22:05 UTC, tribeiro commented on python/lsst/ts/standardscripts/maintel/m1m3/check_actuators.py
> +                    lambda actuator: actuator not in config.ignore_actuators,
lambda functions are not allowed per our development guidelines: https://developer.lsst.io/python/style.html#lambda-should-not-be-used

I would suggest doing something like:

```
self.actuators_to_test = [actuator_id for actuator_id in self.actuators_to_test if actuator_id not in config.ignore_actuators]
```

It is more clear and expressive than the implementation here.

2023-07-11 22:08 UTC, dsanmartim commented on python/lsst/ts/standardscripts/maintel/m1m3/check_actuators.py
> +            default: []
I saw it just after opening the PR. Already fixed it.

2023-07-11 22:31 UTC, tribeiro approved these changes
Looks good! thanks for the updates! please, squash your commits before merging.

2023-07-12 17:02 UTC, dsanmartim commented
Tks for approving it. Merged!

2023-07-12 17:02 UTC, merged